name: continuous-integration

on:
  push:
    branches: ["staging"]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: create env file
        run: |
          touch env.local
          echo "JWT_SECRET_KEY=yeahbuddy!!!!lightweightbaby!!wooooooo" >> env.local
      - name: run backend tests
        run: npm run integration-test
  # test-frontend:
  #   needs: test-backend
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2
  #     - name: run frontend tests
  #       run: npm run unit-test
